version : '3.3'
services :
    backend : 
      image : "${dockerHubUser}/sketch-app:latest"
      ports : 
           - "8000:80"
      networks:
           - my_network
networks:
  my_network:
    external: true
    name: my_network

# docker compose up -d : spins up the container in detached mode.
# docker compose down : stops the container w/o associated name.
# easier for scripts to switch off the container and restart for already running container on port purposes.
