version : '1.1'
services :
    web : 
      image : "yashbhanushali777/sketch-app:latest"
      ports : 
           - "8000:80"

# docker compose up -d : spins up the container in detached mode.
# docker compose down : stops the container w/o associated name.
# easier for scripts to switch off the container and restart for already running container on port purposes.
